repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-merge-conflict
      - id: end-of-file-fixer

  - repo: https://github.com/pycqa/flake8
    rev: 6.1.0
    hooks:
      - id: flake8
        args:
          - --max-line-length=88
          - --ignore=D102,D103,D104,D105,D200,D202,D203,D205,D210,D211,D300,D301,D302,D400,D401,E122,E125,E126,E127,E226,E265,E302,E303,E305,E501,E502,E721,E722,F401,F632,F811,F821,F841,W291,W293,W503,W504,W605
        additional_dependencies: [ ]
        files: \.py$
        exclude: |
          (?x)(
            ^build/.*|
            ^tests/.*|
            ^admin.*|
            .*_ignore\.py$
          )
    
